package com.ohrats.bbb.ohrats;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.widget.TextView;

import java.text.ParseException;
import java.util.Date;

/**
 * Activity which allows the user to view details of an individual RatSighting
 *
 * Created by Matt on 10/9/2017.
 */

public class ViewSightingActivity extends AppCompatActivity{
    private static final boolean useISO8601Display = false;

    //debugging log
    private static final String TAG = "ViewSightingActivity";

    //checks for nulls a lot
    //suppressed because the classes need to be called to get the correct information per sighting
    @SuppressWarnings({"OverlyComplexMethod", "FeatureEnvy", "OverlyLongMethod"})
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_viewsighting);

        // grabs rat sighting object passed with intent
        //suppressed because it grabs each intent and passes it along to a view
        @SuppressWarnings("ChainedMethodCall")
        RatSighting sighting = (RatSighting) getIntent().getSerializableExtra("RAT_SIGHTING");

        // grab text view elements from ui
        TextView mUniqueKey = (TextView) findViewById(R.id.runiquekey);
        TextView mCreatedDate = (TextView) findViewById(R.id.rdate);
        TextView mLocationType = (TextView) findViewById(R.id.rlocationtype);
        TextView mIncidentZip = (TextView) findViewById(R.id.rzip);
        TextView mIncidentAddress = (TextView) findViewById(R.id.raddress);
        TextView mCity = (TextView) findViewById(R.id.rcity);
        TextView mBorough = (TextView) findViewById(R.id.rborough);
        TextView mLatitude = (TextView) findViewById(R.id.rlatitude);
        TextView mLongitude = (TextView) findViewById(R.id.rlongitude);

        mUniqueKey.setText((!("").equals(sighting.getKey())) ? sighting.getKey() : "N/A");
        mLocationType.setText((!("").equals(sighting.getLocationType()))
                ? sighting.getLocationType() : "N/A");
        mIncidentZip.setText((!("").equals(sighting.getZip())) ? sighting.getZip() : "N/A");
        mIncidentAddress.setText((!("").equals(sighting.getAddress()))
                ? sighting.getAddress() : "N/A");
        mCity.setText((!("").equals(sighting.getCity())) ? sighting.getCity() : "N/A");
        mBorough.setText((!("").equals(sighting.getBorough())) ? sighting.getBorough() : "N/A");
        mLatitude.setText((sighting.getLatitude() != 0)
                ? Double.toString(sighting.getLatitude()) : "N/A");
        mLongitude.setText((sighting.getLongitude() != 0)
                ? Double.toString(sighting.getLongitude()) : "N/A");

        if (!("").equals(sighting.getDate())) {
            if (useISO8601Display) {
                String createdDate = sighting.getDate() + R.string.EST;
                mCreatedDate.setText(createdDate);
            } else {
                try {
                    Date dateFromString =
                            DateStandardsBuddy.getDateFromISO8601ESTString(sighting.getDate());
                    String maxIso8601StringFromDate =
                            DateStandardsBuddy.getISO8601MAXStringForDate(dateFromString);
                    String minIso8601StringFromDate =
                            DateStandardsBuddy.getISO8601MINStringForDate(dateFromString);
                    // This output gives the user the date and time to the user in their local time
                    mCreatedDate.setText(dateFromString.toString());
                    Log.d(TAG,
                            "Raw toString from Date generated by parser: "
                                    + dateFromString.toString());
                    Log.d(TAG,
                            "Maximum of "
                                    + sighting.getDate()
                                    + " is : "
                                    + maxIso8601StringFromDate);
                    //----------------------------------
                    Log.d(TAG,
                            "Minimum of "
                                    + sighting.getDate()
                                    + " is : "
                                    + minIso8601StringFromDate);
                    //----------------------------------
                } catch (ParseException e) {
                    Log.d(TAG, "ParseException while trying to parse " + sighting.getDate());
                    // inform the user of bad data
                    String stringError = R.string.Error_Parsing + sighting.getDate();
                    mCreatedDate.setText(stringError);
                }
            }

        }
    }
}
